spring:
  application:
    name: mailapp
  datasource:
    url: jdbc:mysql://localhost:3306/mailapp
    username: root
    password: admin
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          starttls:
            enable: true
          auth: true
    username: <twojmail@gmail.com>
    password: <hasło wygenerowane na https://myaccount.google.com/apppasswords>
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.schema.internal.script.MultiLineSqlScriptExtractor
logging:
  level:
    org.springframework.mail: DEBUG
    org.springframework.mail.javamail: DEBUG